### ISSUE TITLE
Plugin "MMKV Viewer" will stop working after version 0.48 of Flipper released, because it is packaged using the deprecated format.

### ISSUE THREAD

**Issue by yueban** [ddyos/flipper-plugin-mmkv-viewer#3]
When I start Flipper app (0.49) on mac, it shows the warning below.

![image](https://user-images.githubusercontent.com/5647837/87134994-06b71480-c2cc-11ea-8a46-124833bb30f7.png)

BTW, the "MMKV Viewer" is still working, not stop as the warning shows.

**Comment by ddyos** [comment]
Thank you for your feedback.
A new version(1.0.2) is published to npm.

**Comment by yueban** [comment]
After upgrade to version 1.0.2, no more warnings.
